name: build and push Docker images

on:
  workflow_dispatch:
  push:
    tags:
      - 'v**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: meta for Base image
        id: base_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/base
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=tag

      - name: meta for Webserver image
        id: webserver_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/webserver
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=tag

      - name: meta for App image
        id: app_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/app
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=tag

      - name: meta for Queue Worker image
        id: queue_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/queue
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=tag

      - name: meta for Schedule Runner image
        id: schedule_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/schedule
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=tag

      - name: build and push Base image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .docker/Dockerfile
          tags: ${{ steps.base_meta.outputs.tags }}

      - name: build and push Webserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .docker/webserver.Dockerfile
          build-args: |
            "tag=${{ github.ref_name }}"
          tags: ${{ steps.webserver_meta.outputs.tags }}

      - name: build and push App image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .docker/app.Dockerfile
          build-args: |
            "tag=${{ github.ref_name }}"
          tags: ${{ steps.app_meta.outputs.tags }}

      - name: build and push Queue Worker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .docker/queue.Dockerfile
          build-args: |
            "tag=${{ github.ref_name }}"
          tags: ${{ steps.queue_meta.outputs.tags }}

      - name: build and push Schedule Runner image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker
          file: .docker/schedule.Dockerfile
          build-args: |
            "tag=${{ github.ref_name }}"
          tags: ${{ steps.schedule_meta.outputs.tags }}
